# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35ff2c6408c9e4eff55c2695b92dded6baa1584c6493cd5d99d1958f6ab4cbb8c3aee4fa9e6f7d368296cc0785389e48e9c4ddbc45e63e2eba0aefa770c463f4

test:
  secret_key_base: d8e2565777006e006c664b1af156bac9d08959caa29cbbf6d57920316d5739b9148d5eacdbb210e52b0e16d4a155a4b6397e4964d276c8bc3a8a063f57947b3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
